### ISSUE TITLE
When user add a new task then all existing tasks will get deleted automatically.

### ISSUE THREAD

**Issue by Abhishekshelar208** [CSI-DMCE-2024/TODO_APP-Hacktoberfest2024#1]

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?

**Comment by mananKoyawala** [comment]
Hi, I would like to work on this issue to start my open-source journey. Could you let me know if I can take it up?

**Comment by DeadInsane5** [comment]
Hi Maintainers, can I work on this?

**Comment by MDASHHADALI** [comment]
Hello Sir , I can fix this issue. Please assign me.

**Comment by Abhishekshelar208** [comment]
> Hi Maintainers, can I work on this?

@DeadInsane5  yes, go on,

**Comment by DeadInsane5** [comment]
> > Hi Maintainers, can I work on this?
> 
> @DeadInsane5  yes, go on,

Issue is fixed by me and I've created a PR, kindly request you to review the PR
Thanks in advance

**Comment by Abhishekshelar208** [comment]
great job
