### ISSUE TITLE
When user click on add button then this message showing: “Task added successfully” but task is not added into the list.

### ISSUE THREAD

**Issue by Abhishekshelar208** [CSI-DMCE-2024/TODO_APP-Hacktoberfest2024#3]

**Comment by Samyak-Waghmare** [comment]
@Abhishekshelar208 hey, can you assign this issue to me?

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?

**Comment by Abhishekshelar208** [comment]
> Hey leads, can I work on this?

sure

**Comment by Abhishekshelar208** [comment]
> Hey leads, can I work on this?

you have 24 hours to complete it ,as soon as possible

**Comment by DeadInsane5** [comment]
> > Hey leads, can I work on this?
> 
> you have 24 hours to complete it ,as soon as possible

Issue is fixed by me and I've created a PR, kindly request you to review the PR
Thanks in advance

**Comment by DeadInsane5** [comment]
The PR has been merged and closed, kindly requesting Maintainers to close the issue as well
