### ISSUE TITLE
Allow Long press to delete the Task.

### ISSUE THREAD

**Issue by Abhishekshelar208** [CSI-DMCE-2024/TODO_APP-Hacktoberfest2024#7]

**Comment by ArinNigam** [comment]
Can i work on this issue? @Abhishekshelar208

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?

**Comment by TechMe103** [comment]
hey leads , i want to work on this

**Comment by Abhishekshelar208** [comment]
> hey leads , i want to work on this

sure

**Comment by Shreyashjadhav1001** [comment]
Hello Maintainers, I want to work on this issue

**Comment by Abhishekshelar208** [comment]
> Hello Maintainers, I want to work on this issue

yes go ahed.

**Comment by Abhishekshelar208** [comment]
> Hello Maintainers, I want to work on this issue

but make sure that, when long press on any task then show the popup: (are you sure to delete this? ) if they click on yes then delete , okay

**Comment by ArinNigam** [comment]
Can you assign me this issue. I have already opened a PR #10

**Comment by DeadInsane5** [comment]
Hi Maintainers, can I please work on this?

**Comment by Abhishekshelar208** [comment]
> Hi Maintainers, can I please work on this?

yes, but there is one condition: when user long press on it: then show popup called : are you sure to delete this? yes or no, if user click on yes then delete the task

**Comment by DeadInsane5** [comment]
> > Hi Maintainers, can I please work on this?
> 
> yes, but there is one condition: when user long press on it: then show popup called : are you sure to delete this? yes or no, if user click on yes then delete the task

Suree!

**Comment by DeadInsane5** [comment]
> > Hi Maintainers, can I please work on this?
> 
> yes, but there is one condition: when user long press on it: then show popup called : are you sure to delete this? yes or no, if user click on yes then delete the task

Issue is fixed by me and I've created a PR, kindly request you to review the PR
Thanks in advance

**Comment by Abhishekshelar208** [comment]
great job
